### ISSUE TITLE
Calcite colors should appear as a color library not just appearances

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-ui-kits#19]
If I install calcite color I can get to from the appearance panel

![image](https://user-images.githubusercontent.com/378557/66951080-78e51c00-f00e-11e9-8487-b72a494ddbef.png)

But in the color picker it doesn't appear as an option:

![image](https://user-images.githubusercontent.com/378557/66950982-49361400-f00e-11e9-9ade-aeb5e9b90523.png)

Having this absent from the color picker means that you can only pick Calcite colors as fill colors.

**Comment by julio8a** [comment]
@patrickarlt, can you give this another try?

**Comment by julio8a** [comment]
@patrickarlt, can you give this another try. I've pushed files up.
