### ISSUE TITLE
Tooltips shouldn't have caret position baked in

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-ui-kits#21]
Currently tooltips carets are baked into the Tooltip symbol making it impossible to create a tooltip where the caret faces any other way then down.

To create this (for example) I had to unlink tooltip from the library and delete the caret and then used one of the caret symbols.

![image](https://user-images.githubusercontent.com/378557/66952520-a4b5d100-f011-11e9-9dc3-bcd39252e499.png)

**Comment by patrickarlt** [comment]
@macandcheese you could probably just do a symbol with no caret (for the tooltip body) and 4 symbols for each caret direction and just let people compose it however they want too. I'm fine either way. I can imagine ever needing anything other then top, bottom, left, right all centered.

**Comment by julio8a** [comment]
Okay, I've updated on Abstract and this repository. Next, I'm going to separate the popover into its own component in the Sketch library.
