### ISSUE TITLE
Post a link to this calcite - Ui-kit in Figma community

### ISSUE THREAD

**Issue by RoxanneA-alt** [Esri/calcite-ui-kits#38]
Hi there. Thank you from a UX designer and a Question!

I have been creating a design prototype using FIGMA for our developers using the javascript map API.  I have been importing SVG files and recreating components as best I could from the examples in developers.arcgis.com and then voila!! I found this repository.  So grateful!! I usually find UI kits for Figma in the Figma community. I attached a screenshot.  I was wondering if you could publish a link to this repository in Figma Community also?  That way others would find it sooner?  Thanks, again. 

 ![image](https://user-images.githubusercontent.com/67422020/147984800-cd9ce9e9-2841-43cd-8a55-daa4522e8045.png)

**Comment by macandcheese** [comment]
Hi @RoxanneA-alt - so sorry to have missed this. This repository is deprecated and will be archived. An updated version of the Figma UI Kit will be made available in Community in the coming weeks. Thanks!
