### ISSUE TITLE
Calcite-Typography: Error "failed to generate thumbnail" on publishing

### ISSUE THREAD

**Issue by lisastaehli** [Esri/calcite-ui-kits#41]
Hi there 👋 really cool, that you have created this UI kit, it's super useful :) I have already been using the fonts & icons for designs!

I was just trying to add the fonts as well to our own Esri R&D Center Zurich Figma organization following the steps in the README, and got an error when trying to publish the file Calcite-Typography file:

![image](https://user-images.githubusercontent.com/27951811/154998216-1fe3b76c-e5d3-4ef7-931d-b6b57ade6ba3.png)

I am missing something? 🙈 Thanks for your help!

**Reproduction steps**
1. Download Calcite-Typography from this repo
2. Import it to Figma project
3. Click on file & publish
4. Error: "Unable to publish 96 changes to the Team library"

Expected: Typography can be published as a library
Actual: Error message prevents publishing (cannot use the fonts)

NOTE: the console error messages already appear when opening the file in Figma, and they also get thrown when publishing.

**Comment by RoxanneA-alt** [comment]
Hey There--- I'm glad you found the video informative.  I figured out the
calcite Typography problem.  See a new short video here.  Please reach out
if you have any questions.


https://youtu.be/63bpHVhcvfE


Roxanne

**Comment by RoxanneA-alt** [comment]
Hi. I figured it out and published a short video here   
https://youtu.be/63bpHVhcvfE


But basically, make sure you have ALL the Avenir ttf downloaded firstly then go into the edit styles panel for the two offending styles, namely Avenir light and wrapping light and make sure they are set to Avenir not Avenir Next or something else.  The video shows this process.  I hope this helps!! Please reach out if you have any questions.

**Comment by lisastaehli** [comment]
Hi @RoxanneA-alt 😀 thanks so much for the video! This helped a lot.

I am still getting the thumbnail error but the publishing works now! 
I also had to install the local font plugin on Figma, that I didn't know about.
